# Generated by Django 4.2.4 on 2023-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='materno',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='paterno',
        ),
        migrations.AddField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
